//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blok
    {
        public int code { get; set; }
        public Nullable<int> codeTeach { get; set; }
        public Nullable<int> minOfHours { get; set; }
        public Nullable<int> maxOfHours { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
