//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulingEntities : DbContext
    {
        public SchedulingEntities()
            : base("name=SchedulingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blok> Bloks { get; set; }
        public virtual DbSet<IdealHour> IdealHours { get; set; }
        public virtual DbSet<ImpossibleHour> ImpossibleHours { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
    }
}
